Reimplement LogManager sysmodule
Atmosphere-NX/Atmosphere pull request #933
Opened 2020-04-27 20:39 UTC by XorTroll

Reimplements LogManager (LogManager.Prod in retail) sysmodule, redirecting log data to log files in the SD card.
There isn't much left to do (everything seems to work fine), it just needs testing and a proper review.

2020-04-28 06:51 UTC, XorTroll commented
So, one of the aspects I have in my mind right now is the idea of specifying log verbosity via an atmosphere setting, since these logs have many fields which could be logged, but logging all of them (what this reimplementation currently does) might be too verbose for users/devs which just want the text log and don't care about the rest of the fields.

2020-04-28 08:30 UTC, misson20000 commented
I'd rather see logs stores in a machine-readable format for later searching and filtering.

2020-05-10 15:48 UTC, XorTroll commented
This last commit changed many things:
- Now logs are saved in binary format (agree, it's better to save them this way and then parse/print them elsewhere). Save format: `sdmc:/atmosphere/debug_logs/<hex-program-id>/<hex-log-id>.bin`, where the log ID is the current system tick.
- Logs are removed everytime the sysmodule starts (every reboot), since games like Rocket League generate tons of logs which end up wasting a lot of space (in this case, RL generates hundreds of logs just before the title screen is loaded).
- As a way to let other sysmodules/processes get advantage of our logging, added two extra commands to lm service: one to get an event which signals when any process logs, and another one to get the last log's information (log ID and program ID), so that the sysmodule can read the logged data from SD.
- Removed all log packet decoding code, since it is no longer used in LogManager.
As a sidenote, I've tested the extra commands with a simple TCP logger between PC and a sysmodule, and I managed to print everything games/processes log in real time on PC without any issues.

2020-06-28 09:20 UTC, SciresM commented on stratosphere/LogManager/LogManager.json
> +    "main_thread_priority": 10,
This is incorrect. LogManager.MainThread has a system thread priority of 10; this corresponds to an actual hos priority of 38.

2020-06-28 09:20 UTC, SciresM commented on stratosphere/LogManager/LogManager.json
> +            }
Should there be a handle table descriptor to match official LogManager?

2020-06-28 09:21 UTC, SciresM commented on stratosphere/LogManager/source/impl/lm_logging.cpp
> +#include "lm_logging.hpp"
Atmosphere copyright header + #include <stratosphere.hpp>

2020-06-28 09:21 UTC, SciresM commented on stratosphere/LogManager/source/impl/lm_logging.cpp
> +    Result WriteLogPackets(std::vector<LogPacketBuffer> &packet_list) {
std::vector --> no.

2020-06-28 09:24 UTC, SciresM commented on stratosphere/LogManager/source/lm_service.cpp
> +    void Logger::Log(const sf::InAutoSelectBuffer &buf) {
This doesn't seem to match the code RE I've done on lm in the past...

2020-06-28 09:25 UTC, SciresM commented on stratosphere/LogManager/source/lm_types.hpp
> +        TMA = 1,
Atmosphere uses (1 << ...) for bitflag enums.

2020-06-28 09:25 UTC, SciresM commented on stratosphere/Makefile
> +MODULES := loader ncm pm sm boot ams_mitm spl eclct.stub ro creport fatal dmnt boot2 erpt pgl jpegdec LogManager
module should really be called lm (and just have LogManager as npdm name)

2020-06-28 09:26 UTC, SciresM commented on stratosphere/LogManager/source/lm_service.hpp
> +
Atmosphere copyright header, #include <stratosphere.hpp>

2020-06-28 09:26 UTC, SciresM commented on stratosphere/LogManager/source/lm_service.cpp
> +#include "lm_service.hpp"
Atmosphere copyright header, #include <stratosphere.hpp>

2020-06-28 09:26 UTC, SciresM commented on stratosphere/LogManager/source/lm_main.cpp
> +#include "lm_service.hpp"
Atmosphere copyright header, #include <stratosphere.hpp>

2020-06-28 09:26 UTC, SciresM commented on stratosphere/LogManager/source/impl/lm_logging.hpp
> +
Atmosphere copyright header, #include <stratosphere.hpp>

2020-06-28 09:26 UTC, SciresM commented on stratosphere/LogManager/source/lm_types.hpp
> +
Atmosphere copyright header.

2020-06-28 09:27 UTC, SciresM commented on stratosphere/LogManager/source/lm_service.cpp
> +        pminfoGetProgramId(&program_id, static_cast<u64>(client_pid.GetValue()));
This should use the libstratosphere  wrapper.

2020-06-28 09:27 UTC, SciresM commented on stratosphere/LogManager/source/lm_main.cpp
> +    /* TODO: these domain/domain object amounts work fine, but which ones does N actually use? */
Yeah, you should check what N uses.

2021-01-05 20:41 UTC, SciresM requested changes
Reviewed about half the files (no actual lm process code yet).

Mostly stylistic stuff. Do a refactor for the ::detail:: -> ::impl::, ::impl:: -> ::srv:: stuff mentioned before, then I'll do a pass over the lm process code.

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/include/stratosphere/lm/detail/lm_detail_log_packet_transmitter.hpp
> +            using FlushFunction = bool (*)(const void*, size_t);
FlushFunction takes in const u8 *, not const void *.

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/include/stratosphere/lm/detail/lm_detail_log_packet_transmitter.hpp
> +            u8 *log_buffer_start;
Kind of verbose, consider e.g. *start; *end; *payload; *current;

This is not a required change.

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/include/stratosphere/lm/detail/lm_detail_log_packet_transmitter.hpp
> +            LogPacketTransmitterBase(u8 *log_buffer, size_t log_buffer_size, FlushFunction flush_fn, diag::LogSeverity severity, bool verbosity, u64 process_id, bool head, bool tail);
log_buffer should be void *, do not abbreviate function as fn. use "func", if you must..

Severity/verbosity are u8, not enum/bool here.

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/include/stratosphere/fs/fs_sd_card.hpp
> +    Result OpenSdCardDetectionEventNotifier(SdCardDetectionEventNotifier *out);
I will handle this.

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/include/stratosphere/lm/detail/lm_detail_log_packet_transmitter.hpp
> +            static constexpr size_t GetRequiredSizeToPushUleb128(u64 value) {
This seems fake/has messed up access controls. I'll refactor this myself after the detail -> impl changes are made.

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/include/stratosphere/lm/detail/lm_detail_log_packet_transmitter.hpp
> +                u8 dummy_value = 1;
This is actually the boolean value true.

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/include/stratosphere/lm/detail/lm_detail_log_types.hpp
> +        LogDataChunkKey_LogSessionBegin    = 0,  ///< Log session begin.
Atmosphere doesn't use doxygen, shouldn't have doxygen comments.

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/include/stratosphere/lm/detail/lm_detail_log_types.hpp
> +        static constexpr u32 Magic = util::FourCC<'h','p','h','p'>::Code;
Is this the correct endianness?

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/include/stratosphere/lm/detail/lm_detail_log_types.hpp
> +        static constexpr u32 Magic = util::FourCC<'h','p','h','p'>::Code;
Given the code is conceptually "phph" (packet header, packet header), may well do to use reverse code with that encoding.

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/include/stratosphere/lm/detail/lm_detail_log_types.hpp
> +        diag::LogSeverity severity;
should be u8

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/include/stratosphere/lm/detail/lm_detail_log_types.hpp
> +        char verbosity;
should be u8

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/include/stratosphere/lm/detail/lm_detail_log_types.hpp
> +            else {
incorrect formatting for ams style

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/include/stratosphere/lm/detail/lm_detail_log_types.hpp
> +            else {
incorrect formatting for ams style

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/include/stratosphere/lm/detail/lm_detail_log_types.hpp
> +    static_assert(sizeof(LogPacketHeader) == 0x18);
static_assert(util::is_pod<LogPacketHeader>::value);

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/include/stratosphere/lm/lm_api.hpp
> +
gap

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/source/diag/detail/diag_detail_default_log_observer.cpp
> +            "",                /* No special color for Info. */
This is nullptr in Nintendo's implementation, I believe. Should we match?

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/include/stratosphere/diag/detail/diag_detail_log.hpp
> +    void CallAllLogObserver(const LogMetaData &log_metadata, const LogBody &log_body);
It is, but it's internal/not exposed. Why are you exposing it?

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/include/stratosphere/diag/diag_log_observer.hpp
> +    void ResetDefaultLogObserver();
They are, but it's internal/not exposed. Why are you exposing it?

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/source/diag/detail/diag_detail_default_log_observer.cpp
> +        }
line break after here.

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/include/stratosphere/diag/detail/diag_detail_string.hpp
> +    void PrintDebugString(const char *str, size_t len);
It does, but it's internal, and should probably not be exposed.

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/source/diag/detail/diag_detail_default_log_observer.cpp
> +            PrintDebugString(log_body.log_text, log_body.log_text_length);
return PrintDebugString

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/source/diag/detail/diag_detail_default_log_observer.cpp
> +            has_module_name = strlen(log_metadata.module_name) > 1; /* Avoid '$' as module name. */
Comments go on their own lines.

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/source/diag/detail/diag_detail_default_log_observer.cpp
> +        auto has_module_name = false;
...

const auto has_module_name = log_metadata.module_name != nullptr && std::strlen(log_metadata.module_name) > 1?

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/source/diag/detail/diag_detail_default_log_observer.cpp
> +            auto fmt_prefix = (color_type != nullptr) ? color_type : "";
const auto?

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/source/diag/detail/diag_detail_default_log_observer.cpp
> +            auto module_name = log_metadata.module_name;
what type is this? inappropriate auto usage.

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/source/diag/detail/diag_detail_default_log_observer.cpp
> +            auto tick_ts = os::ConvertToTimeSpan(system_tick);
... const auto tick = os::ConvertToTimeSpan(os::GetSystemTick()); ?

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/source/diag/detail/diag_detail_default_log_observer.cpp
> +        else if (color_type) {
invalid else format

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/source/diag/detail/diag_detail_default_log_observer.cpp
> +        else if (color_type) {
color_type != nullptr

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/source/diag/detail/diag_detail_default_log_observer.cpp
> +        auto fmt_prefix = (color_type != nullptr) ? "\x1B[0m" : "";
Why is this a local variable, and not e.g. a constexpr variable which is ternary'd in the SNPrintf call?

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/source/diag/detail/diag_detail_default_log_observer.cpp
> +        auto left_buffer_space = sizeof(g_default_log_observer_text_buffer) - used_buffer_space;
...const auto max_buffer_size = sizeof(....) - used_buffer_space - (color_type != nullptr ? std::strlen(ResetColorType) - 1 : 0)

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/source/diag/detail/diag_detail_default_log_observer.cpp
> +        auto log_text_size = std::min(left_buffer_space, log_body.log_text_length);
const auto, specify that it's std::min<size_t>

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/source/diag/detail/diag_detail_log.cpp
> +        void PutCharacters(void *user_data, const char *chars, int chars_len) {
This needs comments, to not use auto everywhere, to use const where appropriate...

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/source/fs/fs_sd_card.cpp
> +        R_TRY(fsEventNotifierGetEventHandle(static_cast<FsEventNotifier *>(this->notifier), std::addressof(event), clear_mode == os::EventClearMode_AutoClear));
This needs fixes, which I'll do.

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/source/diag/diag_log_observer.cpp
> +namespace ams::diag {
This and the other log observer file should really be a single translation unit. I'll handle the merge.

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/source/lm/detail/lm_detail_log_observer.cpp
> +        u8 g_packet_transmitter_buffer[0x400];
You only have a single buffer, N has a unit heap of 4, but I can handle this.

2021-01-05 20:41 UTC, SciresM commented on libraries/libstratosphere/source/lm/detail/lm_detail_log_observer.cpp
> +    void LogManagerLogObserver(const diag::LogMetaData &log_metadata, const diag::LogBody &log_body, void *user_data) {
This (and other code) creates lots of locals that are non-const and never used again. Better off with immediates.

2021-09-23 17:36 UTC, closed without merging